FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-nanoserver-1803 AS base

LABEL maintainer='https://github.com/shivayl'

WORKDIR /app
EXPOSE 69 
EXPOSE 443
COPY . .

# RUN dir .

ENTRYPOINT [ "Braces.PluginHost/bin/debug/netcoreapp3.0/Braces.PluginHost.exe" ] 
